#!/bin/sh

# Find netcat command or die
NC=$(command -v netcat || command -v nc || exit 1)

DOCKER_SOCKET=/var/run/docker.sock

CONFIG_FILE=/etc/zabbix/scripts/trapper/docker.conf

[ -r "$CONFIG_FILE" ] && . $CONFIG_FILE

CTS=$(printf "GET /containers/json?all=1 HTTP/1.0\r\n\r\n"|sudo $NC -U "$DOCKER_SOCKET"|tail -n 1)
LEN=$(echo "$CTS"|jq 'length')

for I in $(seq 0 $((LEN-1)))
do
    NAME=$(echo "$CTS"|jq ".[$I].Names[0]"|sed -e 's/^"\//"/')
    DATA="$DATA,"'{"{#NAME}":'$NAME'}'

done
echo '{"data":['${DATA#,}']}'
